### ISSUE TITLE
NetOptions.instance 怎么修改 contentType multipart/form-data create中写死了

### ISSUE THREAD

**Issue by wuxinggege008** [yuexunshi/flutter_net#11]
/// 配置网络请求并初始化
  void create() {
    var httpConfig = _httpConfigBuilder.create();
    if (httpConfig.interceptors?.isNotEmpty ?? false) {
      _dio.interceptors.addAll(httpConfig.interceptors!);
    }
    if (_isLogger) {
      dio.interceptors.add(PrettyDioLogger(
          requestHeader: true,
          requestBody: true,
          responseBody: true,
          responseHeader: false,
          error: true,
          compact: true,
          maxWidth: 90
      ));
    }
    _dio.options = BaseOptions(
        baseUrl: httpConfig.baseUrl ?? '',
        contentType: 'application/json',
        connectTimeout: httpConfig.connectTimeout,
        sendTimeout: httpConfig.sendTimeout,
        receiveTimeout: httpConfig.receiveTimeout,
        headers: httpConfig.headers);
    if (httpConfig.httpClientAdapter != null) {
      _dio.httpClientAdapter = httpConfig.httpClientAdapter!;
    }
  }

**Comment by GeraintLeee** [comment]
上传文件的话直接data:FormData.fromMap()就可以了，我也是摸索了半天
