### ISSUE TITLE
如何在 failure 中拿到错误的响应信息

### ISSUE THREAD

**Issue by JackXueX** [yuexunshi/flutter_net#12]
<img width="869" alt="image" src="https://github.com/yuexunshi/flutter_net/assets/42790406/a169dc25-804f-45ea-98e6-7304ce59ebc1">

如图，在code为400，failure 中的msg并没有返回的错误信息

**Comment by hancens1024** [comment]
NetOptions.instance.dio.options.validateStatus = (_) => true;
