### ISSUE TITLE
还是没看懂为什么需要泛型，只在decodeType传一个泛型的实例不行吗，为什么还要在前面加两个泛型的实例？

### ISSUE THREAD

**Issue by xiaoyao20084321** [yuexunshi/flutter_net#7]
看您文章里说了，泛型可以不写。。那这两个有啥用啊？麻烦解答一下，感激不尽。
<img width="815" alt="image" src="https://github.com/yuexunshi/flutter_net/assets/10344550/7bf36411-de91-4dd1-bd85-13b8b909c318">

**Comment by yuexunshi** [comment]
写泛型是为了解析的时候利用泛型获取类型，不写是因为可以从回调中的类型推导出来。所以也可以不写。类似val a =0;和 int  a = 0;
